-- CreateEnum
CREATE TYPE "AchievimentKey" AS ENUM ('FIRST_LOGIN', 'NO_ERRORS', 'MISS_ONE', 'REGISTERED_POST', 'REGISTERED_10_POST', 'REGISTERED_30_POST', 'EDIT_PROFILE', 'PLAYED_QUIZ', 'PLAYED_QUIZ_5', 'PLAYED_QUIZ_15', 'READ_PROGRAM', 'READ_5_PROGRAM', 'READ_15_PROGRAM', 'ASKED_BOT', 'LOGGED_10_TIMES_IN_ROW', 'LOGGED_50_TIMES_IN_ROW', 'LOGGED_100_TIMES_IN_ROW');

-- AlterTable
ALTER TABLE "Achieviment" ADD COLUMN     "key" "AchievimentKey";
